version: '3.9'

services:
  postgres:
    image: postgres:16
    container_name: txprocessor-postgres
    environment:
      POSTGRES_DB: txdb
      POSTGRES_USER: txuser
      POSTGRES_PASSWORD: txpass
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: