# -------------------------------------------------
# Application
# -------------------------------------------------
spring.application.name=txprocessor

# -------------------------------------------------
# R2DBC (Reactive runtime)
# -------------------------------------------------
#spring.r2dbc.url=r2dbc:postgresql://localhost:5432/txdb
#spring.r2dbc.username=txuser
#spring.r2dbc.password=txpass

# -------------------------------------------------
# Liquibase (JDBC - schema management)
# -------------------------------------------------
spring.liquibase.enabled=true
#spring.liquibase.url=jdbc:postgresql://localhost:5432/txdb
#spring.liquibase.user=txuser
#spring.liquibase.password=txpass
spring.liquibase.change-log=classpath:/db/changelog/db.changelog-master.yaml

# -------------------------------------------------
# Disable SQL auto-init (Liquibase owns the schema)
# -------------------------------------------------
spring.sql.init.mode=never

# -------------------------------------------------
# Logging (useful for local debugging)
# -------------------------------------------------
logging.level.org.springframework.r2dbc=INFO
logging.level.liquibase=INFO
logging.level.org.postgresql=INFO